// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TES.Business.Entity
{ 
    public partial class Speakers
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Profile { get; set; }
        public string LinkedInUrl { get; set; }
        public string Twitter { get; set; }
        public string Pic { get; set; }
    }
}