// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using TES.Business.Entity;

namespace TES.Data.Entity
{
    public partial class TESContext : DbContext
    {
        public TESContext()
        {
        }

        public TESContext(DbContextOptions<TESContext> options)
            : base(options)
        {
        }

        public DbSet<Events> Events { get; set; }
        public DbSet<Speakers> Speakers { get; set; }
        public DbSet<TalkDetails> TalkDetails { get; set; }
        public DbSet<Venue> Venue { get; set; }
    }
}