// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OSS.Business.Entity
{
    public class Categories
    {
        public Categories()
        {
            FootwaerDetails = new HashSet<FootwearDetails>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Pic { get; set; }

        public virtual ICollection<FootwearDetails> FootwaerDetails { get; set; }
    }
}