// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Business.Entity
{
    public partial class Course
    {
        //public Course()
        //{
        //    Enrollment = new HashSet<Enrollment>();
        //}

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }

        //public virtual ICollection<Enrollment> Enrollment { get; set; }
    }
}